# Generated by Django 4.2.4 on 2023-09-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(upload_to='avatares'),
        ),
    ]
