# Generated by Django 4.2.4 on 2023-09-08 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_usuario_avatar_user_alter_avatar_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Clase',
        ),
    ]
