# Generated by Django 4.2.4 on 2023-09-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_curso_clase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Instructor',
        ),
    ]
