# Generated by Django 4.2.4 on 2023-09-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_profesor_instructor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Alumno',
        ),
    ]
