# Generated by Django 4.2.4 on 2023-09-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_estudiante_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='duracion',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
