# Generated by Django 4.2.4 on 2023-09-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_clase_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='hobbie',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
