# Generated by Django 4.2.4 on 2023-09-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_alumno_hobbie_alumno_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechaproxima',
            name='duracion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
